---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: activities-build-pipeline
  namespace: ocp-pipelines
spec:
  params:
    - name: git-url
      default: "https://github.com/florient2016/Activities.git"
    - name: git-revision
      default: "latest"
    - name: image-repo
      default: "docker.io/komlan2019/activities"
  workspaces:
    - name: shared-workspace
  tasks:
    - name: clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: build-and-push
      taskRef:
        name: buildah
      runAfter: [clone]
      params:
        - name: IMAGE
          #value: "$(params.image-repo):$(params.git-revision)"
          value: "$(params.image-repo):latest"  # Forces tag to "latest"
        - name: DOCKERFILE
          value: "./Dockerfile"
      workspaces:
        - name: source
          workspace: shared-workspace