apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ocp-deployment-pipeline
  namespace: ocp-pipelines
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "secrets", "configmaps","serviceaccounts","persistentvolumeclaims","namespaces","persistentvolumes","routes","events"]
    verbs: ["create", "update", "patch", "delete", "get", "list", "watch"]
  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch", "escalate"]
  - apiGroups: ["tekton.dev"]
    resources: ["pipelines", "tasks", "pipelineruns", "runs", "pipelineresources", "taskruns","triggerbindings","triggertemplates","eventlisteners","clustertriggerbindings"]
    verbs: ["get", "list", "create", "update", "delete", "watch", "escalate", "bind", "patch"]
  - apiGroups: ["*.tekton.dev"]
    resources: ["pipelines", "tasks", "pipelineruns", "runs", "pipelineresources", "taskruns","triggerbindings","triggertemplates","eventlisteners","clustertriggerbindings"]
    verbs: ["get", "list", "create", "update", "delete", "watch", "escalate", "bind", "patch"]
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["pipelines", "tasks", "pipelineruns", "runs", "pipelineresources", "taskruns","triggerbindings","triggertemplates","eventlisteners","clustertriggerbindings"]
    verbs: ["get", "list", "create", "update", "delete", "watch", "escalate", "bind", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ocp-deployment-pipeline
  namespace: ocp-pipelines
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  kind: Role
  name: ocp-deployment-pipeline
  apiGroup: rbac.authorization.k8s.io